
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.golite.parser;

import java_cup.runtime.*;
import com.golite.ast.NodoAST;
import com.golite.ast.sentencias.*;
import com.golite.ast.expresiones.*;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\004\000\002\002\011\000\002\003" +
    "\004\000\002\003\005\000\002\003\005\000\002\003\002" +
    "\000\002\015\003\000\002\015\002\000\002\004\004\000" +
    "\002\004\004\000\002\004\003\000\002\004\003\000\002" +
    "\004\004\000\002\004\003\000\002\004\004\000\002\004" +
    "\004\000\002\004\005\000\002\010\007\000\002\010\005" +
    "\000\002\010\005\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\011\005\000\002\011\005\000\002\011\005\000\002\011" +
    "\004\000\002\011\004\000\002\012\007\000\002\012\013" +
    "\000\002\012\011\000\002\013\007\000\002\013\013\000" +
    "\002\014\006\000\002\014\005\000\002\016\007\000\002" +
    "\016\012\000\002\017\004\000\002\017\002\000\002\020" +
    "\006\000\002\006\005\000\002\006\003\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\005\000\002\005" +
    "\005\000\002\005\005\000\002\005\005\000\002\005\004" +
    "\000\002\005\004\000\002\005\005\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\006\000\002\005\006\000\002\005\012" +
    "\000\002\005\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\004\005\004\001\002\000\004\006\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\057\010\001\002\000\004\060\011\001\002\000" +
    "\004\061\012\001\002\000\030\003\ufffc\004\ufffc\007\ufffc" +
    "\011\ufffc\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062" +
    "\ufffc\071\ufffc\001\002\000\030\003\025\004\035\007\017" +
    "\011\031\012\024\013\014\015\016\027\023\061\020\062" +
    "\015\071\021\001\002\000\036\003\ufffa\004\ufffa\007\ufffa" +
    "\011\ufffa\012\ufffa\013\ufffa\015\ufffa\016\ufffa\017\ufffa\027" +
    "\ufffa\061\ufffa\062\ufffa\066\140\071\ufffa\001\002\000\004" +
    "\002\000\001\002\000\036\020\047\030\053\031\050\032" +
    "\055\034\046\056\061\057\062\071\054\072\056\073\064" +
    "\074\057\075\051\076\052\077\063\001\002\000\036\020" +
    "\047\030\053\031\050\032\055\034\046\056\061\057\062" +
    "\071\054\072\056\073\064\074\057\075\051\076\052\077" +
    "\063\001\002\000\030\003\ufffc\004\ufffc\007\ufffc\011\ufffc" +
    "\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062\ufffc\071" +
    "\ufffc\001\002\000\016\040\165\041\166\042\167\043\151" +
    "\044\164\045\163\001\002\000\034\003\ufff4\004\ufff4\007" +
    "\ufff4\011\ufff4\012\ufff4\013\ufff4\015\ufff4\016\ufff4\017\ufff4" +
    "\027\ufff4\061\ufff4\062\ufff4\071\ufff4\001\002\000\004\057" +
    "\177\001\002\000\036\003\ufffa\004\ufffa\007\ufffa\011\ufffa" +
    "\012\ufffa\013\ufffa\015\ufffa\016\ufffa\017\ufffa\027\ufffa\061" +
    "\ufffa\062\ufffa\066\140\071\ufffa\001\002\000\006\062\175" +
    "\066\174\001\002\000\036\003\ufffa\004\ufffa\007\ufffa\011" +
    "\ufffa\012\ufffa\013\ufffa\015\ufffa\016\ufffa\017\ufffa\027\ufffa" +
    "\061\ufffa\062\ufffa\066\140\071\ufffa\001\002\000\034\003" +
    "\ufff7\004\ufff7\007\ufff7\011\ufff7\012\ufff7\013\ufff7\015\ufff7" +
    "\016\ufff7\017\ufff7\027\ufff7\061\ufff7\062\ufff7\071\ufff7\001" +
    "\002\000\034\003\ufff6\004\ufff6\007\ufff6\011\ufff6\012\ufff6" +
    "\013\ufff6\015\ufff6\016\ufff6\017\ufff6\027\ufff6\061\ufff6\062" +
    "\ufff6\071\ufff6\001\002\000\040\004\035\020\047\030\053" +
    "\031\050\032\055\034\046\056\061\057\062\071\144\072" +
    "\056\073\064\074\057\075\051\076\052\077\063\001\002" +
    "\000\036\003\ufffa\004\ufffa\007\ufffa\011\ufffa\012\ufffa\013" +
    "\ufffa\015\ufffa\016\ufffa\017\ufffa\027\ufffa\061\ufffa\062\ufffa" +
    "\066\140\071\ufffa\001\002\000\036\003\ufffa\004\ufffa\007" +
    "\ufffa\011\ufffa\012\ufffa\013\ufffa\015\ufffa\016\ufffa\017\ufffa" +
    "\027\ufffa\061\ufffa\062\ufffa\066\140\071\ufffa\001\002\000" +
    "\034\003\uffff\004\uffff\007\uffff\011\uffff\012\uffff\013\uffff" +
    "\015\uffff\016\uffff\017\uffff\027\uffff\061\uffff\062\uffff\071" +
    "\uffff\001\002\000\004\071\036\001\002\000\014\022\037" +
    "\023\040\024\044\025\043\026\042\001\002\000\040\003" +
    "\uffed\004\uffed\007\uffed\011\uffed\012\uffed\013\uffed\015\uffed" +
    "\016\uffed\017\uffed\027\uffed\042\uffed\061\uffed\062\uffed\066" +
    "\uffed\071\uffed\001\002\000\040\003\uffec\004\uffec\007\uffec" +
    "\011\uffec\012\uffec\013\uffec\015\uffec\016\uffec\017\uffec\027" +
    "\uffec\042\uffec\061\uffec\062\uffec\066\uffec\071\uffec\001\002" +
    "\000\040\003\uffef\004\uffef\007\uffef\011\uffef\012\uffef\013" +
    "\uffef\015\uffef\016\uffef\017\uffef\027\uffef\042\045\061\uffef" +
    "\062\uffef\066\uffef\071\uffef\001\002\000\040\003\uffe9\004" +
    "\uffe9\007\uffe9\011\uffe9\012\uffe9\013\uffe9\015\uffe9\016\uffe9" +
    "\017\uffe9\027\uffe9\042\uffe9\061\uffe9\062\uffe9\066\uffe9\071" +
    "\uffe9\001\002\000\040\003\uffea\004\uffea\007\uffea\011\uffea" +
    "\012\uffea\013\uffea\015\uffea\016\uffea\017\uffea\027\uffea\042" +
    "\uffea\061\uffea\062\uffea\066\uffea\071\uffea\001\002\000\040" +
    "\003\uffeb\004\uffeb\007\uffeb\011\uffeb\012\uffeb\013\uffeb\015" +
    "\uffeb\016\uffeb\017\uffeb\027\uffeb\042\uffeb\061\uffeb\062\uffeb" +
    "\066\uffeb\071\uffeb\001\002\000\036\020\047\030\053\031" +
    "\050\032\055\034\046\056\061\057\062\071\054\072\056" +
    "\073\064\074\057\075\051\076\052\077\063\001\002\000" +
    "\036\020\047\030\053\031\050\032\055\034\046\056\061" +
    "\057\062\071\054\072\056\073\064\074\057\075\051\076" +
    "\052\077\063\001\002\000\076\003\uffc0\004\uffc0\007\uffc0" +
    "\011\uffc0\012\uffc0\013\uffc0\015\uffc0\016\uffc0\017\uffc0\027" +
    "\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0\037\uffc0\046\uffc0" +
    "\047\uffc0\050\uffc0\051\uffc0\052\uffc0\053\uffc0\054\uffc0\055" +
    "\uffc0\060\uffc0\061\uffc0\062\uffc0\065\uffc0\066\uffc0\070\uffc0" +
    "\071\uffc0\001\002\000\004\057\134\001\002\000\076\003" +
    "\uffc2\004\uffc2\007\uffc2\011\uffc2\012\uffc2\013\uffc2\015\uffc2" +
    "\016\uffc2\017\uffc2\027\uffc2\033\uffc2\034\uffc2\035\uffc2\036" +
    "\uffc2\037\uffc2\046\uffc2\047\uffc2\050\uffc2\051\uffc2\052\uffc2" +
    "\053\uffc2\054\uffc2\055\uffc2\060\uffc2\061\uffc2\062\uffc2\065" +
    "\uffc2\066\uffc2\070\uffc2\071\uffc2\001\002\000\076\003\uffc1" +
    "\004\uffc1\007\uffc1\011\uffc1\012\uffc1\013\uffc1\015\uffc1\016" +
    "\uffc1\017\uffc1\027\uffc1\033\uffc1\034\uffc1\035\uffc1\036\uffc1" +
    "\037\uffc1\046\uffc1\047\uffc1\050\uffc1\051\uffc1\052\uffc1\053" +
    "\uffc1\054\uffc1\055\uffc1\060\uffc1\061\uffc1\062\uffc1\065\uffc1" +
    "\066\uffc1\070\uffc1\071\uffc1\001\002\000\004\057\131\001" +
    "\002\000\076\003\uffbe\004\uffbe\007\uffbe\011\uffbe\012\uffbe" +
    "\013\uffbe\015\uffbe\016\uffbe\017\uffbe\027\uffbe\033\uffbe\034" +
    "\uffbe\035\uffbe\036\uffbe\037\uffbe\046\uffbe\047\uffbe\050\uffbe" +
    "\051\uffbe\052\uffbe\053\uffbe\054\uffbe\055\uffbe\060\uffbe\061" +
    "\uffbe\062\uffbe\065\uffbe\066\uffbe\070\uffbe\071\uffbe\001\002" +
    "\000\004\057\122\001\002\000\076\003\uffc3\004\uffc3\007" +
    "\uffc3\011\uffc3\012\uffc3\013\uffc3\015\uffc3\016\uffc3\017\uffc3" +
    "\027\uffc3\033\uffc3\034\uffc3\035\uffc3\036\uffc3\037\uffc3\046" +
    "\uffc3\047\uffc3\050\uffc3\051\uffc3\052\uffc3\053\uffc3\054\uffc3" +
    "\055\uffc3\060\uffc3\061\uffc3\062\uffc3\065\uffc3\066\uffc3\070" +
    "\uffc3\071\uffc3\001\002\000\076\003\uffc4\004\uffc4\007\uffc4" +
    "\011\uffc4\012\uffc4\013\uffc4\015\uffc4\016\uffc4\017\uffc4\027" +
    "\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\046\uffc4" +
    "\047\uffc4\050\uffc4\051\uffc4\052\uffc4\053\uffc4\054\uffc4\055" +
    "\uffc4\060\uffc4\061\uffc4\062\uffc4\065\uffc4\066\uffc4\070\uffc4" +
    "\071\uffc4\001\002\000\070\003\ufff0\004\ufff0\007\ufff0\011" +
    "\ufff0\012\ufff0\013\ufff0\015\ufff0\016\ufff0\017\ufff0\027\ufff0" +
    "\033\073\034\067\035\077\036\075\037\070\046\072\047" +
    "\071\050\101\051\074\052\103\053\100\054\066\055\102" +
    "\061\ufff0\062\ufff0\066\ufff0\071\ufff0\001\002\000\036\020" +
    "\047\030\053\031\050\032\055\034\046\056\061\057\062" +
    "\071\054\072\056\073\064\074\057\075\051\076\052\077" +
    "\063\001\002\000\036\020\047\030\053\031\050\032\055" +
    "\034\046\056\061\057\062\071\054\072\056\073\064\074" +
    "\057\075\051\076\052\077\063\001\002\000\076\003\uffbf" +
    "\004\uffbf\007\uffbf\011\uffbf\012\uffbf\013\uffbf\015\uffbf\016" +
    "\uffbf\017\uffbf\027\uffbf\033\uffbf\034\uffbf\035\uffbf\036\uffbf" +
    "\037\uffbf\046\uffbf\047\uffbf\050\uffbf\051\uffbf\052\uffbf\053" +
    "\uffbf\054\uffbf\055\uffbf\060\uffbf\061\uffbf\062\uffbf\065\uffbf" +
    "\066\uffbf\070\uffbf\071\uffbf\001\002\000\076\003\uffc5\004" +
    "\uffc5\007\uffc5\011\uffc5\012\uffc5\013\uffc5\015\uffc5\016\uffc5" +
    "\017\uffc5\027\uffc5\033\uffc5\034\uffc5\035\uffc5\036\uffc5\037" +
    "\uffc5\046\uffc5\047\uffc5\050\uffc5\051\uffc5\052\uffc5\053\uffc5" +
    "\054\uffc5\055\uffc5\060\uffc5\061\uffc5\062\uffc5\065\uffc5\066" +
    "\uffc5\070\uffc5\071\uffc5\001\002\000\036\033\073\034\067" +
    "\035\077\036\075\037\070\046\072\047\071\050\101\051" +
    "\074\052\103\053\100\054\066\055\102\060\076\001\002" +
    "\000\036\020\047\030\053\031\050\032\055\034\046\056" +
    "\061\057\062\071\054\072\056\073\064\074\057\075\051" +
    "\076\052\077\063\001\002\000\036\020\047\030\053\031" +
    "\050\032\055\034\046\056\061\057\062\071\054\072\056" +
    "\073\064\074\057\075\051\076\052\077\063\001\002\000" +
    "\036\020\047\030\053\031\050\032\055\034\046\056\061" +
    "\057\062\071\054\072\056\073\064\074\057\075\051\076" +
    "\052\077\063\001\002\000\036\020\047\030\053\031\050" +
    "\032\055\034\046\056\061\057\062\071\054\072\056\073" +
    "\064\074\057\075\051\076\052\077\063\001\002\000\036" +
    "\020\047\030\053\031\050\032\055\034\046\056\061\057" +
    "\062\071\054\072\056\073\064\074\057\075\051\076\052" +
    "\077\063\001\002\000\036\020\047\030\053\031\050\032" +
    "\055\034\046\056\061\057\062\071\054\072\056\073\064" +
    "\074\057\075\051\076\052\077\063\001\002\000\036\020" +
    "\047\030\053\031\050\032\055\034\046\056\061\057\062" +
    "\071\054\072\056\073\064\074\057\075\051\076\052\077" +
    "\063\001\002\000\036\020\047\030\053\031\050\032\055" +
    "\034\046\056\061\057\062\071\054\072\056\073\064\074" +
    "\057\075\051\076\052\077\063\001\002\000\076\003\uffc6" +
    "\004\uffc6\007\uffc6\011\uffc6\012\uffc6\013\uffc6\015\uffc6\016" +
    "\uffc6\017\uffc6\027\uffc6\033\uffc6\034\uffc6\035\uffc6\036\uffc6" +
    "\037\uffc6\046\uffc6\047\uffc6\050\uffc6\051\uffc6\052\uffc6\053" +
    "\uffc6\054\uffc6\055\uffc6\060\uffc6\061\uffc6\062\uffc6\065\uffc6" +
    "\066\uffc6\070\uffc6\071\uffc6\001\002\000\036\020\047\030" +
    "\053\031\050\032\055\034\046\056\061\057\062\071\054" +
    "\072\056\073\064\074\057\075\051\076\052\077\063\001" +
    "\002\000\036\020\047\030\053\031\050\032\055\034\046" +
    "\056\061\057\062\071\054\072\056\073\064\074\057\075" +
    "\051\076\052\077\063\001\002\000\036\020\047\030\053" +
    "\031\050\032\055\034\046\056\061\057\062\071\054\072" +
    "\056\073\064\074\057\075\051\076\052\077\063\001\002" +
    "\000\036\020\047\030\053\031\050\032\055\034\046\056" +
    "\061\057\062\071\054\072\056\073\064\074\057\075\051" +
    "\076\052\077\063\001\002\000\036\020\047\030\053\031" +
    "\050\032\055\034\046\056\061\057\062\071\054\072\056" +
    "\073\064\074\057\075\051\076\052\077\063\001\002\000" +
    "\076\003\uffcc\004\uffcc\007\uffcc\011\uffcc\012\uffcc\013\uffcc" +
    "\015\uffcc\016\uffcc\017\uffcc\027\uffcc\033\073\034\067\035" +
    "\077\036\075\037\070\046\uffcc\047\uffcc\050\uffcc\051\uffcc" +
    "\052\uffcc\053\uffcc\054\uffcc\055\uffcc\060\uffcc\061\uffcc\062" +
    "\uffcc\065\uffcc\066\uffcc\070\uffcc\071\uffcc\001\002\000\076" +
    "\003\uffc9\004\uffc9\007\uffc9\011\uffc9\012\uffc9\013\uffc9\015" +
    "\uffc9\016\uffc9\017\uffc9\027\uffc9\033\073\034\067\035\077" +
    "\036\075\037\070\046\072\047\071\050\101\051\074\052" +
    "\103\053\100\054\066\055\uffc9\060\uffc9\061\uffc9\062\uffc9" +
    "\065\uffc9\066\uffc9\070\uffc9\071\uffc9\001\002\000\076\003" +
    "\uffce\004\uffce\007\uffce\011\uffce\012\uffce\013\uffce\015\uffce" +
    "\016\uffce\017\uffce\027\uffce\033\073\034\067\035\077\036" +
    "\075\037\070\046\uffce\047\uffce\050\uffce\051\uffce\052\uffce" +
    "\053\uffce\054\uffce\055\uffce\060\uffce\061\uffce\062\uffce\065" +
    "\uffce\066\uffce\070\uffce\071\uffce\001\002\000\076\003\uffcb" +
    "\004\uffcb\007\uffcb\011\uffcb\012\uffcb\013\uffcb\015\uffcb\016" +
    "\uffcb\017\uffcb\027\uffcb\033\073\034\067\035\077\036\075" +
    "\037\070\046\uffcb\047\uffcb\050\uffcb\051\uffcb\052\uffcb\053" +
    "\uffcb\054\uffcb\055\uffcb\060\uffcb\061\uffcb\062\uffcb\065\uffcb" +
    "\066\uffcb\070\uffcb\071\uffcb\001\002\000\076\003\uffd3\004" +
    "\uffd3\007\uffd3\011\uffd3\012\uffd3\013\uffd3\015\uffd3\016\uffd3" +
    "\017\uffd3\027\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\037" +
    "\uffd3\046\uffd3\047\uffd3\050\uffd3\051\uffd3\052\uffd3\053\uffd3" +
    "\054\uffd3\055\uffd3\060\uffd3\061\uffd3\062\uffd3\065\uffd3\066" +
    "\uffd3\070\uffd3\071\uffd3\001\002\000\076\003\uffd2\004\uffd2" +
    "\007\uffd2\011\uffd2\012\uffd2\013\uffd2\015\uffd2\016\uffd2\017" +
    "\uffd2\027\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2" +
    "\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052\uffd2\053\uffd2\054" +
    "\uffd2\055\uffd2\060\uffd2\061\uffd2\062\uffd2\065\uffd2\066\uffd2" +
    "\070\uffd2\071\uffd2\001\002\000\076\003\uffcd\004\uffcd\007" +
    "\uffcd\011\uffcd\012\uffcd\013\uffcd\015\uffcd\016\uffcd\017\uffcd" +
    "\027\uffcd\033\073\034\067\035\077\036\075\037\070\046" +
    "\uffcd\047\uffcd\050\uffcd\051\uffcd\052\uffcd\053\uffcd\054\uffcd" +
    "\055\uffcd\060\uffcd\061\uffcd\062\uffcd\065\uffcd\066\uffcd\070" +
    "\uffcd\071\uffcd\001\002\000\076\003\uffd5\004\uffd5\007\uffd5" +
    "\011\uffd5\012\uffd5\013\uffd5\015\uffd5\016\uffd5\017\uffd5\027" +
    "\uffd5\033\uffd5\034\uffd5\035\077\036\075\037\070\046\uffd5" +
    "\047\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5\055" +
    "\uffd5\060\uffd5\061\uffd5\062\uffd5\065\uffd5\066\uffd5\070\uffd5" +
    "\071\uffd5\001\002\000\076\003\uffd0\004\uffd0\007\uffd0\011" +
    "\uffd0\012\uffd0\013\uffd0\015\uffd0\016\uffd0\017\uffd0\027\uffd0" +
    "\033\073\034\067\035\077\036\075\037\070\046\uffd0\047" +
    "\uffd0\050\101\051\074\052\103\053\100\054\uffd0\055\uffd0" +
    "\060\uffd0\061\uffd0\062\uffd0\065\uffd0\066\uffd0\070\uffd0\071" +
    "\uffd0\001\002\000\076\003\uffcf\004\uffcf\007\uffcf\011\uffcf" +
    "\012\uffcf\013\uffcf\015\uffcf\016\uffcf\017\uffcf\027\uffcf\033" +
    "\073\034\067\035\077\036\075\037\070\046\uffcf\047\uffcf" +
    "\050\101\051\074\052\103\053\100\054\uffcf\055\uffcf\060" +
    "\uffcf\061\uffcf\062\uffcf\065\uffcf\066\uffcf\070\uffcf\071\uffcf" +
    "\001\002\000\076\003\uffd1\004\uffd1\007\uffd1\011\uffd1\012" +
    "\uffd1\013\uffd1\015\uffd1\016\uffd1\017\uffd1\027\uffd1\033\uffd1" +
    "\034\uffd1\035\uffd1\036\uffd1\037\uffd1\046\uffd1\047\uffd1\050" +
    "\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055\uffd1\060\uffd1" +
    "\061\uffd1\062\uffd1\065\uffd1\066\uffd1\070\uffd1\071\uffd1\001" +
    "\002\000\076\003\uffd4\004\uffd4\007\uffd4\011\uffd4\012\uffd4" +
    "\013\uffd4\015\uffd4\016\uffd4\017\uffd4\027\uffd4\033\uffd4\034" +
    "\uffd4\035\077\036\075\037\070\046\uffd4\047\uffd4\050\uffd4" +
    "\051\uffd4\052\uffd4\053\uffd4\054\uffd4\055\uffd4\060\uffd4\061" +
    "\uffd4\062\uffd4\065\uffd4\066\uffd4\070\uffd4\071\uffd4\001\002" +
    "\000\076\003\uffca\004\uffca\007\uffca\011\uffca\012\uffca\013" +
    "\uffca\015\uffca\016\uffca\017\uffca\027\uffca\033\073\034\067" +
    "\035\077\036\075\037\070\046\072\047\071\050\101\051" +
    "\074\052\103\053\100\054\uffca\055\uffca\060\uffca\061\uffca" +
    "\062\uffca\065\uffca\066\uffca\070\uffca\071\uffca\001\002\000" +
    "\076\003\uffc8\004\uffc8\007\uffc8\011\uffc8\012\uffc8\013\uffc8" +
    "\015\uffc8\016\uffc8\017\uffc8\027\uffc8\033\uffc8\034\uffc8\035" +
    "\uffc8\036\uffc8\037\uffc8\046\uffc8\047\uffc8\050\uffc8\051\uffc8" +
    "\052\uffc8\053\uffc8\054\uffc8\055\uffc8\060\uffc8\061\uffc8\062" +
    "\uffc8\065\uffc8\066\uffc8\070\uffc8\071\uffc8\001\002\000\036" +
    "\020\047\030\053\031\050\032\055\034\046\056\061\057" +
    "\062\071\054\072\056\073\064\074\057\075\051\076\052" +
    "\077\063\001\002\000\036\033\073\034\067\035\077\036" +
    "\075\037\070\046\072\047\071\050\101\051\074\052\103" +
    "\053\100\054\066\055\102\060\124\001\002\000\100\003" +
    "\uffba\004\uffba\007\uffba\011\uffba\012\uffba\013\uffba\015\uffba" +
    "\016\uffba\017\uffba\027\uffba\033\uffba\034\uffba\035\uffba\036" +
    "\uffba\037\uffba\046\uffba\047\uffba\050\uffba\051\uffba\052\uffba" +
    "\053\uffba\054\uffba\055\uffba\060\uffba\061\uffba\062\uffba\065" +
    "\uffba\066\uffba\067\125\070\uffba\071\uffba\001\002\000\004" +
    "\071\126\001\002\000\004\057\127\001\002\000\004\060" +
    "\130\001\002\000\076\003\uffbb\004\uffbb\007\uffbb\011\uffbb" +
    "\012\uffbb\013\uffbb\015\uffbb\016\uffbb\017\uffbb\027\uffbb\033" +
    "\uffbb\034\uffbb\035\uffbb\036\uffbb\037\uffbb\046\uffbb\047\uffbb" +
    "\050\uffbb\051\uffbb\052\uffbb\053\uffbb\054\uffbb\055\uffbb\060" +
    "\uffbb\061\uffbb\062\uffbb\065\uffbb\066\uffbb\070\uffbb\071\uffbb" +
    "\001\002\000\036\020\047\030\053\031\050\032\055\034" +
    "\046\056\061\057\062\071\054\072\056\073\064\074\057" +
    "\075\051\076\052\077\063\001\002\000\036\033\073\034" +
    "\067\035\077\036\075\037\070\046\072\047\071\050\101" +
    "\051\074\052\103\053\100\054\066\055\102\060\133\001" +
    "\002\000\076\003\uffbd\004\uffbd\007\uffbd\011\uffbd\012\uffbd" +
    "\013\uffbd\015\uffbd\016\uffbd\017\uffbd\027\uffbd\033\uffbd\034" +
    "\uffbd\035\uffbd\036\uffbd\037\uffbd\046\uffbd\047\uffbd\050\uffbd" +
    "\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd\060\uffbd\061" +
    "\uffbd\062\uffbd\065\uffbd\066\uffbd\070\uffbd\071\uffbd\001\002" +
    "\000\036\020\047\030\053\031\050\032\055\034\046\056" +
    "\061\057\062\071\054\072\056\073\064\074\057\075\051" +
    "\076\052\077\063\001\002\000\036\033\073\034\067\035" +
    "\077\036\075\037\070\046\072\047\071\050\101\051\074" +
    "\052\103\053\100\054\066\055\102\060\136\001\002\000" +
    "\076\003\uffbc\004\uffbc\007\uffbc\011\uffbc\012\uffbc\013\uffbc" +
    "\015\uffbc\016\uffbc\017\uffbc\027\uffbc\033\uffbc\034\uffbc\035" +
    "\uffbc\036\uffbc\037\uffbc\046\uffbc\047\uffbc\050\uffbc\051\uffbc" +
    "\052\uffbc\053\uffbc\054\uffbc\055\uffbc\060\uffbc\061\uffbc\062" +
    "\uffbc\065\uffbc\066\uffbc\070\uffbc\071\uffbc\001\002\000\076" +
    "\003\uffc7\004\uffc7\007\uffc7\011\uffc7\012\uffc7\013\uffc7\015" +
    "\uffc7\016\uffc7\017\uffc7\027\uffc7\033\uffc7\034\uffc7\035\uffc7" +
    "\036\uffc7\037\uffc7\046\uffc7\047\uffc7\050\uffc7\051\uffc7\052" +
    "\uffc7\053\uffc7\054\uffc7\055\uffc7\060\uffc7\061\uffc7\062\uffc7" +
    "\065\uffc7\066\uffc7\070\uffc7\071\uffc7\001\002\000\034\003" +
    "\ufffb\004\ufffb\007\ufffb\011\ufffb\012\ufffb\013\ufffb\015\ufffb" +
    "\016\ufffb\017\ufffb\027\ufffb\061\ufffb\062\ufffb\071\ufffb\001" +
    "\002\000\034\003\ufff8\004\ufff8\007\ufff8\011\ufff8\012\ufff8" +
    "\013\ufff8\015\ufff8\016\ufff8\017\ufff8\027\ufff8\061\ufff8\062" +
    "\ufff8\071\ufff8\001\002\000\034\003\ufff9\004\ufff9\007\ufff9" +
    "\011\ufff9\012\ufff9\013\ufff9\015\ufff9\016\ufff9\017\ufff9\027" +
    "\ufff9\061\ufff9\062\ufff9\071\ufff9\001\002\000\004\066\153" +
    "\001\002\000\040\033\uffbe\034\uffbe\035\uffbe\036\uffbe\037" +
    "\uffbe\043\151\046\uffbe\047\uffbe\050\uffbe\051\uffbe\052\uffbe" +
    "\053\uffbe\054\uffbe\055\uffbe\061\uffbe\001\002\000\036\033" +
    "\073\034\067\035\077\036\075\037\070\046\072\047\071" +
    "\050\101\051\074\052\103\053\100\054\066\055\102\061" +
    "\146\001\002\000\030\003\ufffc\004\ufffc\007\ufffc\011\ufffc" +
    "\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062\ufffc\071" +
    "\ufffc\001\002\000\030\003\025\004\035\007\017\011\031" +
    "\012\024\013\014\015\016\027\023\061\020\062\150\071" +
    "\021\001\002\000\034\003\uffe0\004\uffe0\007\uffe0\011\uffe0" +
    "\012\uffe0\013\uffe0\015\uffe0\016\uffe0\017\uffe0\027\uffe0\061" +
    "\uffe0\062\uffe0\071\uffe0\001\002\000\036\020\047\030\053" +
    "\031\050\032\055\034\046\056\061\057\062\071\054\072" +
    "\056\073\064\074\057\075\051\076\052\077\063\001\002" +
    "\000\070\003\uffee\004\uffee\007\uffee\011\uffee\012\uffee\013" +
    "\uffee\015\uffee\016\uffee\017\uffee\027\uffee\033\073\034\067" +
    "\035\077\036\075\037\070\046\072\047\071\050\101\051" +
    "\074\052\103\053\100\054\066\055\102\061\uffee\062\uffee" +
    "\066\uffee\071\uffee\001\002\000\036\020\047\030\053\031" +
    "\050\032\055\034\046\056\061\057\062\071\054\072\056" +
    "\073\064\074\057\075\051\076\052\077\063\001\002\000" +
    "\036\033\073\034\067\035\077\036\075\037\070\046\072" +
    "\047\071\050\101\051\074\052\103\053\100\054\066\055" +
    "\102\066\155\001\002\000\004\071\156\001\002\000\014" +
    "\040\165\041\166\042\167\044\164\045\163\001\002\000" +
    "\004\061\160\001\002\000\030\003\ufffc\004\ufffc\007\ufffc" +
    "\011\ufffc\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062" +
    "\ufffc\071\ufffc\001\002\000\030\003\025\004\035\007\017" +
    "\011\031\012\024\013\014\015\016\027\023\061\020\062" +
    "\162\071\021\001\002\000\034\003\uffdf\004\uffdf\007\uffdf" +
    "\011\uffdf\012\uffdf\013\uffdf\015\uffdf\016\uffdf\017\uffdf\027" +
    "\uffdf\061\uffdf\062\uffdf\071\uffdf\001\002\000\036\020\047" +
    "\030\053\031\050\032\055\034\046\056\061\057\062\071" +
    "\054\072\056\073\064\074\057\075\051\076\052\077\063" +
    "\001\002\000\036\020\047\030\053\031\050\032\055\034" +
    "\046\056\061\057\062\071\054\072\056\073\064\074\057" +
    "\075\051\076\052\077\063\001\002\000\036\003\uffe5\004" +
    "\uffe5\007\uffe5\011\uffe5\012\uffe5\013\uffe5\015\uffe5\016\uffe5" +
    "\017\uffe5\027\uffe5\061\uffe5\062\uffe5\066\uffe5\071\uffe5\001" +
    "\002\000\036\003\uffe4\004\uffe4\007\uffe4\011\uffe4\012\uffe4" +
    "\013\uffe4\015\uffe4\016\uffe4\017\uffe4\027\uffe4\061\uffe4\062" +
    "\uffe4\066\uffe4\071\uffe4\001\002\000\036\020\047\030\053" +
    "\031\050\032\055\034\046\056\061\057\062\071\054\072" +
    "\056\073\064\074\057\075\051\076\052\077\063\001\002" +
    "\000\070\003\uffe8\004\uffe8\007\uffe8\011\uffe8\012\uffe8\013" +
    "\uffe8\015\uffe8\016\uffe8\017\uffe8\027\uffe8\033\073\034\067" +
    "\035\077\036\075\037\070\046\072\047\071\050\101\051" +
    "\074\052\103\053\100\054\066\055\102\061\uffe8\062\uffe8" +
    "\066\uffe8\071\uffe8\001\002\000\070\003\uffe7\004\uffe7\007" +
    "\uffe7\011\uffe7\012\uffe7\013\uffe7\015\uffe7\016\uffe7\017\uffe7" +
    "\027\uffe7\033\073\034\067\035\077\036\075\037\070\046" +
    "\072\047\071\050\101\051\074\052\103\053\100\054\066" +
    "\055\102\061\uffe7\062\uffe7\066\uffe7\071\uffe7\001\002\000" +
    "\070\003\uffe6\004\uffe6\007\uffe6\011\uffe6\012\uffe6\013\uffe6" +
    "\015\uffe6\016\uffe6\017\uffe6\027\uffe6\033\073\034\067\035" +
    "\077\036\075\037\070\046\072\047\071\050\101\051\074" +
    "\052\103\053\100\054\066\055\102\061\uffe6\062\uffe6\066" +
    "\uffe6\071\uffe6\001\002\000\034\003\ufff5\004\ufff5\007\ufff5" +
    "\011\ufff5\012\ufff5\013\ufff5\015\ufff5\016\ufff5\017\ufff5\027" +
    "\ufff5\061\ufff5\062\ufff5\071\ufff5\001\002\000\034\003\ufffe" +
    "\004\ufffe\007\ufffe\011\ufffe\012\ufffe\013\ufffe\015\ufffe\016" +
    "\ufffe\017\ufffe\027\ufffe\061\ufffe\062\ufffe\071\ufffe\001\002" +
    "\000\034\003\ufffd\004\ufffd\007\ufffd\011\ufffd\012\ufffd\013" +
    "\ufffd\015\ufffd\016\ufffd\017\ufffd\027\ufffd\061\ufffd\062\ufffd" +
    "\071\ufffd\001\002\000\034\003\ufff3\004\ufff3\007\ufff3\011" +
    "\ufff3\012\ufff3\013\ufff3\015\ufff3\016\ufff3\017\ufff3\027\ufff3" +
    "\061\ufff3\062\ufff3\071\ufff3\001\002\000\040\020\047\030" +
    "\053\031\050\032\055\034\046\056\061\057\062\060\201" +
    "\071\054\072\056\073\064\074\057\075\051\076\052\077" +
    "\063\001\002\000\006\060\204\065\203\001\002\000\036" +
    "\003\uffdd\004\uffdd\007\uffdd\011\uffdd\012\uffdd\013\uffdd\015" +
    "\uffdd\016\uffdd\017\uffdd\027\uffdd\061\uffdd\062\uffdd\066\uffdd" +
    "\071\uffdd\001\002\000\040\033\073\034\067\035\077\036" +
    "\075\037\070\046\072\047\071\050\101\051\074\052\103" +
    "\053\100\054\066\055\102\060\uffd6\065\uffd6\001\002\000" +
    "\036\020\047\030\053\031\050\032\055\034\046\056\061" +
    "\057\062\071\054\072\056\073\064\074\057\075\051\076" +
    "\052\077\063\001\002\000\036\003\uffde\004\uffde\007\uffde" +
    "\011\uffde\012\uffde\013\uffde\015\uffde\016\uffde\017\uffde\027" +
    "\uffde\061\uffde\062\uffde\066\uffde\071\uffde\001\002\000\040" +
    "\033\073\034\067\035\077\036\075\037\070\046\072\047" +
    "\071\050\101\051\074\052\103\053\100\054\066\055\102" +
    "\060\uffd7\065\uffd7\001\002\000\030\003\025\004\035\007" +
    "\017\011\031\012\024\013\014\015\016\027\023\061\020" +
    "\062\207\071\021\001\002\000\034\003\ufff1\004\ufff1\007" +
    "\ufff1\011\ufff1\012\ufff1\013\ufff1\015\ufff1\016\ufff1\017\ufff1" +
    "\027\ufff1\061\ufff1\062\ufff1\071\ufff1\001\002\000\036\033" +
    "\073\034\067\035\077\036\075\037\070\046\072\047\071" +
    "\050\101\051\074\052\103\053\100\054\066\055\102\061" +
    "\211\001\002\000\030\003\ufffc\004\ufffc\007\ufffc\011\ufffc" +
    "\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062\ufffc\071" +
    "\ufffc\001\002\000\030\003\025\004\035\007\017\011\031" +
    "\012\024\013\014\015\016\027\023\061\020\062\213\071" +
    "\021\001\002\000\036\003\uffe3\004\uffe3\007\uffe3\010\214" +
    "\011\uffe3\012\uffe3\013\uffe3\015\uffe3\016\uffe3\017\uffe3\027" +
    "\uffe3\061\uffe3\062\uffe3\071\uffe3\001\002\000\006\007\017" +
    "\061\215\001\002\000\030\003\ufffc\004\ufffc\007\ufffc\011" +
    "\ufffc\012\ufffc\013\ufffc\015\ufffc\027\ufffc\061\ufffc\062\ufffc" +
    "\071\ufffc\001\002\000\034\003\uffe1\004\uffe1\007\uffe1\011" +
    "\uffe1\012\uffe1\013\uffe1\015\uffe1\016\uffe1\017\uffe1\027\uffe1" +
    "\061\uffe1\062\uffe1\071\uffe1\001\002\000\030\003\025\004" +
    "\035\007\017\011\031\012\024\013\014\015\016\027\023" +
    "\061\020\062\220\071\021\001\002\000\034\003\uffe2\004" +
    "\uffe2\007\uffe2\011\uffe2\012\uffe2\013\uffe2\015\uffe2\016\uffe2" +
    "\017\uffe2\027\uffe2\061\uffe2\062\uffe2\071\uffe2\001\002\000" +
    "\036\033\073\034\067\035\077\036\075\037\070\046\072" +
    "\047\071\050\101\051\074\052\103\053\100\054\066\055" +
    "\102\061\222\001\002\000\010\016\uffd9\017\uffd9\062\uffd9" +
    "\001\002\000\010\016\227\017\224\062\225\001\002\000" +
    "\004\070\233\001\002\000\034\003\uffdc\004\uffdc\007\uffdc" +
    "\011\uffdc\012\uffdc\013\uffdc\015\uffdc\016\uffdc\017\uffdc\027" +
    "\uffdc\061\uffdc\062\uffdc\071\uffdc\001\002\000\010\016\uffda" +
    "\017\uffda\062\uffda\001\002\000\036\020\047\030\053\031" +
    "\050\032\055\034\046\056\061\057\062\071\054\072\056" +
    "\073\064\074\057\075\051\076\052\077\063\001\002\000" +
    "\036\033\073\034\067\035\077\036\075\037\070\046\072" +
    "\047\071\050\101\051\074\052\103\053\100\054\066\055" +
    "\102\070\231\001\002\000\034\003\ufffc\004\ufffc\007\ufffc" +
    "\011\ufffc\012\ufffc\013\ufffc\015\ufffc\016\ufffc\017\ufffc\027" +
    "\ufffc\061\ufffc\062\ufffc\071\ufffc\001\002\000\034\003\025" +
    "\004\035\007\017\011\031\012\024\013\014\015\016\016" +
    "\uffd8\017\uffd8\027\023\061\020\062\uffd8\071\021\001\002" +
    "\000\030\003\ufffc\004\ufffc\007\ufffc\011\ufffc\012\ufffc\013" +
    "\ufffc\015\ufffc\027\ufffc\061\ufffc\062\ufffc\071\ufffc\001\002" +
    "\000\030\003\025\004\035\007\017\011\031\012\024\013" +
    "\014\015\016\027\023\061\020\062\235\071\021\001\002" +
    "\000\034\003\uffdb\004\uffdb\007\uffdb\011\uffdb\012\uffdb\013" +
    "\uffdb\015\uffdb\016\uffdb\017\uffdb\027\uffdb\061\uffdb\062\uffdb" +
    "\071\uffdb\001\002\000\034\003\ufff2\004\ufff2\007\ufff2\011" +
    "\ufff2\012\ufff2\013\ufff2\015\ufff2\016\ufff2\017\ufff2\027\ufff2" +
    "\061\ufff2\062\ufff2\071\ufff2\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\012\001\001\000" +
    "\020\004\033\010\031\011\032\012\026\013\027\014\025" +
    "\016\021\001\001\000\004\015\235\001\001\000\002\001" +
    "\001\000\004\005\220\001\001\000\004\005\207\001\001" +
    "\000\004\003\205\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\175\001\001\000\002" +
    "\001\001\000\004\015\172\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\005\144\010\142\001\001\000\004" +
    "\015\141\001\001\000\004\015\140\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\040\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\057" +
    "\001\001\000\004\005\136\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\120" +
    "\001\001\000\004\005\064\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\117\001\001" +
    "\000\004\005\116\001\001\000\004\005\115\001\001\000" +
    "\004\005\114\001\001\000\004\005\113\001\001\000\004" +
    "\005\112\001\001\000\004\005\111\001\001\000\004\005" +
    "\110\001\001\000\002\001\001\000\004\005\107\001\001" +
    "\000\004\005\106\001\001\000\004\005\105\001\001\000" +
    "\004\005\104\001\001\000\004\005\103\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\122\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\131\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\134\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\146\001\001\000\020\004\033\010\031\011\032\012\026" +
    "\013\027\014\025\016\021\001\001\000\002\001\001\000" +
    "\004\005\151\001\001\000\002\001\001\000\004\005\153" +
    "\001\001\000\002\001\001\000\004\011\156\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\160\001\001" +
    "\000\020\004\033\010\031\011\032\012\026\013\027\014" +
    "\025\016\021\001\001\000\002\001\001\000\004\005\171" +
    "\001\001\000\004\005\170\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\167\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\201\006\177\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\204\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\004\033\010\031\011" +
    "\032\012\026\013\027\014\025\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\211\001\001\000" +
    "\020\004\033\010\031\011\032\012\026\013\027\014\025" +
    "\016\021\001\001\000\002\001\001\000\004\012\215\001" +
    "\001\000\004\003\216\001\001\000\002\001\001\000\020" +
    "\004\033\010\031\011\032\012\026\013\027\014\025\016" +
    "\021\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\017\222\001\001\000\004\020\225\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\227" +
    "\001\001\000\002\001\001\000\004\003\231\001\001\000" +
    "\020\004\033\010\031\011\032\012\026\013\027\014\025" +
    "\016\021\001\001\000\004\003\233\001\001\000\020\004" +
    "\033\010\031\011\032\012\026\013\027\014\025\016\021" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(java_cup.runtime.Symbol s) {
        String val = s.value != null ? s.value.toString() : "desconocido";
        String msg = "Error sintactico cerca de '" + val + "'";
        com.golite.interpreter.Interprete.getInstancia()
            .agregarError(msg, s.left, s.right, "sintactico");
    }

    public void unrecovered_syntax_error(java_cup.runtime.Symbol s) {
        String val = s.value != null ? s.value.toString() : "desconocido";
        String msg = "Error sintactico no recuperable cerca de '" + val + "'";
        com.golite.interpreter.Interprete.getInstancia()
            .agregarError(msg, s.left, s.right, "sintactico");
    }

    public void report_error(String message, Object info) { }
    public void report_fatal_error(String message, Object info) { }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoPrograma start_val = (NodoPrograma)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= FUNC MAIN LPAREN RPAREN LBRACE stmt_list RBRACE 
            {
              NodoPrograma RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> s = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoPrograma(s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // stmt_list ::= stmt_list stmt 
            {
              List<NodoAST> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST s = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 if (s != null) { sl.add(s); } RESULT = sl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt_list ::= stmt_list error SEMICOLON 
            {
              List<NodoAST> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = sl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt_list ::= stmt_list error RBRACE 
            {
              List<NodoAST> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = sl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt_list ::= 
            {
              List<NodoAST> RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // opt_semi ::= SEMICOLON 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // opt_semi ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= decl_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST d = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= assign_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAsignacion a = (NodoAsignacion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= if_stmt 
            {
              NodoAST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoIf i = (NodoIf)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= for_stmt 
            {
              NodoAST RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST f = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= print_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST p = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= switch_stmt 
            {
              NodoAST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST s = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= BREAK opt_semi 
            {
              NodoAST RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoBreak(bleft, bright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= CONTINUE opt_semi 
            {
              NodoAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoContinue(cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoBloque(sl, 0, 0); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // decl_stmt ::= VAR ID tipo ASSIGN expr 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, t, e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // decl_stmt ::= VAR ID tipo 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, t, null, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // decl_stmt ::= ID DECL_ASSIGN expr 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, null, e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= TINT 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo ::= TFLOAT64 
            {
              String RESULT =null;
		 RESULT = "float64"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo ::= TSTRING 
            {
              String RESULT =null;
		 RESULT = "string"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= TBOOL 
            {
              String RESULT =null;
		 RESULT = "bool"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= TRUNE 
            {
              String RESULT =null;
		 RESULT = "rune"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // assign_stmt ::= ID ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // assign_stmt ::= ID PLUS_ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "+=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // assign_stmt ::= ID MINUS_ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "-=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // assign_stmt ::= ID INC 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAsignacion(n, "+=", new NodoEntero(1, nleft, nright), nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // assign_stmt ::= ID DEC 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAsignacion(n, "-=", new NodoEntero(1, nleft, nright), nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // if_stmt ::= IF expr LBRACE stmt_list RBRACE 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoIf(c, t, null, null, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // if_stmt ::= IF expr LBRACE stmt_list RBRACE ELSE LBRACE stmt_list RBRACE 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> e = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoIf(c, t, e, null, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // if_stmt ::= IF expr LBRACE stmt_list RBRACE ELSE if_stmt 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eiright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoIf ei = (NodoIf)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoIf(c, t, null, ei, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // for_stmt ::= FOR expr LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> b = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoFor(c, null, null, b, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // for_stmt ::= FOR decl_stmt SEMICOLON expr SEMICOLON assign_stmt LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		NodoAST i = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAsignacion u = (NodoAsignacion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> b = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoFor(c, i, u, b, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // print_stmt ::= PRINTLN LPAREN expr_list RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> args = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoPrintln(args, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("print_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // print_stmt ::= PRINTLN LPAREN RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new NodoPrintln(new ArrayList<>(), pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("print_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // switch_stmt ::= SWITCH expr LBRACE case_list RBRACE 
            {
              NodoAST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> cl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoSwitch(e, cl, null, sleft, sright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("switch_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // switch_stmt ::= SWITCH expr LBRACE case_list DEFAULT COLON stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		List<NodoAST> cl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int dlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> dl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoSwitch(e, cl, dl, sleft, sright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("switch_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // case_list ::= case_list case_clause 
            {
              List<NodoAST> RESULT =null;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> cl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 cl.add(c); RESULT = cl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_list",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // case_list ::= 
            {
              List<NodoAST> RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_list",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // case_clause ::= CASE expr COLON stmt_list 
            {
              NodoAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCaso(e, sl, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_clause",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr_list ::= expr_list COMMA expr 
            {
              List<NodoAST> RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoAST> el = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 el.add(e); RESULT = el; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr_list ::= expr 
            {
              List<NodoAST> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<NodoAST> l = new ArrayList<>(); l.add(e); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr PLUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoSuma(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr MINUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoResta(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr TIMES expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoMultiplicacion(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr DIV expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDivision(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr MOD expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoModulo(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr EQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "==", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr NEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "!=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr LT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "<",  b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr GT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, ">",  b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr LEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "<=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= expr GEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, ">=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr AND expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "&&", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr OR expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "||", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= NOT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "!", null, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= MINUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoNegacion(a, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= INT_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoEntero(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= FLOAT_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double v = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDecimal(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= STRING_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoString(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= TRUE 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Boolean v = (Boolean)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoBooleano(true,  vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= FALSE 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Boolean v = (Boolean)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoBooleano(false, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= NIL 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoEntero(0, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= RUNE_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Character v = (Character)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoRune(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= ID 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoIdentificador(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= ATOI LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAtoi(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr ::= PARSEFLOAT LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoParseFloat(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr ::= TYPEOF LPAREN expr RPAREN DOT ID LPAREN RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		 RESULT = new NodoTypeOf(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr ::= TYPEOF LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoTypeOf(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
