
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.golite.parser;

import java_cup.runtime.*;
import com.golite.ast.NodoAST;
import com.golite.ast.sentencias.*;
import com.golite.ast.expresiones.*;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\004\000\002\002\011\000\002\003" +
    "\004\000\002\003\002\000\002\015\003\000\002\015\002" +
    "\000\002\004\004\000\002\004\004\000\002\004\003\000" +
    "\002\004\003\000\002\004\004\000\002\004\004\000\002" +
    "\004\004\000\002\004\005\000\002\010\007\000\002\010" +
    "\005\000\002\010\005\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\011\005\000\002\011\005\000\002\011\005\000\002" +
    "\011\004\000\002\011\004\000\002\012\007\000\002\012" +
    "\013\000\002\012\011\000\002\013\007\000\002\013\013" +
    "\000\002\014\006\000\002\014\005\000\002\006\005\000" +
    "\002\006\003\000\002\005\005\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\005\000\002\005" +
    "\005\000\002\005\005\000\002\005\005\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\004\000\002\005\004\000\002" +
    "\005\005\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\006\000" +
    "\002\005\006\000\002\005\012" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\212\000\004\005\004\001\002\000\004\006\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\054\010\001\002\000\004\055\011\001\002\000" +
    "\004\056\012\001\002\000\024\004\ufffe\007\ufffe\011\ufffe" +
    "\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe\063\ufffe\001" +
    "\002\000\024\004\023\007\024\011\016\012\032\013\026" +
    "\024\022\056\015\057\030\063\025\001\002\000\026\004" +
    "\ufffc\007\ufffc\011\ufffc\012\ufffc\013\ufffc\024\ufffc\056\ufffc" +
    "\057\ufffc\061\033\063\ufffc\001\002\000\024\004\ufffe\007" +
    "\ufffe\011\ufffe\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe" +
    "\063\ufffe\001\002\000\040\004\023\015\046\025\053\026" +
    "\047\027\054\031\045\053\056\054\061\063\175\064\055" +
    "\065\063\066\060\067\050\070\051\071\062\001\002\000" +
    "\024\004\ufff9\007\ufff9\011\ufff9\012\ufff9\013\ufff9\024\ufff9" +
    "\056\ufff9\057\ufff9\063\ufff9\001\002\000\024\004\uffff\007" +
    "\uffff\011\uffff\012\uffff\013\uffff\024\uffff\056\uffff\057\uffff" +
    "\063\uffff\001\002\000\026\004\ufffc\007\ufffc\011\ufffc\012" +
    "\ufffc\013\ufffc\024\ufffc\056\ufffc\057\ufffc\061\033\063\ufffc" +
    "\001\002\000\004\054\164\001\002\000\004\063\153\001" +
    "\002\000\036\015\046\025\053\026\047\027\054\031\045" +
    "\053\056\054\061\063\052\064\055\065\063\066\060\067" +
    "\050\070\051\071\062\001\002\000\016\035\042\036\043" +
    "\037\044\040\041\041\040\042\037\001\002\000\026\004" +
    "\ufffc\007\ufffc\011\ufffc\012\ufffc\013\ufffc\024\ufffc\056\ufffc" +
    "\057\ufffc\061\033\063\ufffc\001\002\000\026\004\ufffc\007" +
    "\ufffc\011\ufffc\012\ufffc\013\ufffc\024\ufffc\056\ufffc\057\ufffc" +
    "\061\033\063\ufffc\001\002\000\004\002\000\001\002\000" +
    "\024\004\ufff8\007\ufff8\011\ufff8\012\ufff8\013\ufff8\024\ufff8" +
    "\056\ufff8\057\ufff8\063\ufff8\001\002\000\026\004\ufffc\007" +
    "\ufffc\011\ufffc\012\ufffc\013\ufffc\024\ufffc\056\ufffc\057\ufffc" +
    "\061\033\063\ufffc\001\002\000\024\004\ufffd\007\ufffd\011" +
    "\ufffd\012\ufffd\013\ufffd\024\ufffd\056\ufffd\057\ufffd\063\ufffd" +
    "\001\002\000\024\004\ufff6\007\ufff6\011\ufff6\012\ufff6\013" +
    "\ufff6\024\ufff6\056\ufff6\057\ufff6\063\ufff6\001\002\000\024" +
    "\004\ufff7\007\ufff7\011\ufff7\012\ufff7\013\ufff7\024\ufff7\056" +
    "\ufff7\057\ufff7\063\ufff7\001\002\000\024\004\ufff5\007\ufff5" +
    "\011\ufff5\012\ufff5\013\ufff5\024\ufff5\056\ufff5\057\ufff5\063" +
    "\ufff5\001\002\000\036\015\046\025\053\026\047\027\054" +
    "\031\045\053\056\054\061\063\052\064\055\065\063\066" +
    "\060\067\050\070\051\071\062\001\002\000\036\015\046" +
    "\025\053\026\047\027\054\031\045\053\056\054\061\063" +
    "\052\064\055\065\063\066\060\067\050\070\051\071\062" +
    "\001\002\000\036\015\046\025\053\026\047\027\054\031" +
    "\045\053\056\054\061\063\052\064\055\065\063\066\060" +
    "\067\050\070\051\071\062\001\002\000\026\004\uffe8\007" +
    "\uffe8\011\uffe8\012\uffe8\013\uffe8\024\uffe8\056\uffe8\057\uffe8" +
    "\061\uffe8\063\uffe8\001\002\000\026\004\uffe7\007\uffe7\011" +
    "\uffe7\012\uffe7\013\uffe7\024\uffe7\056\uffe7\057\uffe7\061\uffe7" +
    "\063\uffe7\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\036\015" +
    "\046\025\053\026\047\027\054\031\045\053\056\054\061" +
    "\063\052\064\055\065\063\066\060\067\050\070\051\071" +
    "\062\001\002\000\064\004\uffc8\007\uffc8\011\uffc8\012\uffc8" +
    "\013\uffc8\024\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8\034" +
    "\uffc8\043\uffc8\044\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8" +
    "\051\uffc8\052\uffc8\055\uffc8\056\uffc8\057\uffc8\060\uffc8\061" +
    "\uffc8\063\uffc8\001\002\000\004\054\133\001\002\000\064" +
    "\004\uffca\007\uffca\011\uffca\012\uffca\013\uffca\024\uffca\030" +
    "\uffca\031\uffca\032\uffca\033\uffca\034\uffca\043\uffca\044\uffca" +
    "\045\uffca\046\uffca\047\uffca\050\uffca\051\uffca\052\uffca\055" +
    "\uffca\056\uffca\057\uffca\060\uffca\061\uffca\063\uffca\001\002" +
    "\000\064\004\uffc9\007\uffc9\011\uffc9\012\uffc9\013\uffc9\024" +
    "\uffc9\030\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\043\uffc9" +
    "\044\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051\uffc9\052" +
    "\uffc9\055\uffc9\056\uffc9\057\uffc9\060\uffc9\061\uffc9\063\uffc9" +
    "\001\002\000\064\004\uffc6\007\uffc6\011\uffc6\012\uffc6\013" +
    "\uffc6\024\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6\034\uffc6" +
    "\043\uffc6\044\uffc6\045\uffc6\046\uffc6\047\uffc6\050\uffc6\051" +
    "\uffc6\052\uffc6\055\uffc6\056\uffc6\057\uffc6\060\uffc6\061\uffc6" +
    "\063\uffc6\001\002\000\004\054\130\001\002\000\004\054" +
    "\121\001\002\000\064\004\uffcb\007\uffcb\011\uffcb\012\uffcb" +
    "\013\uffcb\024\uffcb\030\uffcb\031\uffcb\032\uffcb\033\uffcb\034" +
    "\uffcb\043\uffcb\044\uffcb\045\uffcb\046\uffcb\047\uffcb\050\uffcb" +
    "\051\uffcb\052\uffcb\055\uffcb\056\uffcb\057\uffcb\060\uffcb\061" +
    "\uffcb\063\uffcb\001\002\000\036\015\046\025\053\026\047" +
    "\027\054\031\045\053\056\054\061\063\052\064\055\065" +
    "\063\066\060\067\050\070\051\071\062\001\002\000\060" +
    "\004\uffeb\007\uffeb\011\uffeb\012\uffeb\013\uffeb\024\uffeb\030" +
    "\072\031\066\032\076\033\074\034\067\043\071\044\070" +
    "\045\077\046\073\047\102\050\100\051\065\052\101\056" +
    "\uffeb\057\uffeb\061\uffeb\063\uffeb\001\002\000\064\004\uffcc" +
    "\007\uffcc\011\uffcc\012\uffcc\013\uffcc\024\uffcc\030\uffcc\031" +
    "\uffcc\032\uffcc\033\uffcc\034\uffcc\043\uffcc\044\uffcc\045\uffcc" +
    "\046\uffcc\047\uffcc\050\uffcc\051\uffcc\052\uffcc\055\uffcc\056" +
    "\uffcc\057\uffcc\060\uffcc\061\uffcc\063\uffcc\001\002\000\036" +
    "\015\046\025\053\026\047\027\054\031\045\053\056\054" +
    "\061\063\052\064\055\065\063\066\060\067\050\070\051" +
    "\071\062\001\002\000\064\004\uffc7\007\uffc7\011\uffc7\012" +
    "\uffc7\013\uffc7\024\uffc7\030\uffc7\031\uffc7\032\uffc7\033\uffc7" +
    "\034\uffc7\043\uffc7\044\uffc7\045\uffc7\046\uffc7\047\uffc7\050" +
    "\uffc7\051\uffc7\052\uffc7\055\uffc7\056\uffc7\057\uffc7\060\uffc7" +
    "\061\uffc7\063\uffc7\001\002\000\064\004\uffcd\007\uffcd\011" +
    "\uffcd\012\uffcd\013\uffcd\024\uffcd\030\uffcd\031\uffcd\032\uffcd" +
    "\033\uffcd\034\uffcd\043\uffcd\044\uffcd\045\uffcd\046\uffcd\047" +
    "\uffcd\050\uffcd\051\uffcd\052\uffcd\055\uffcd\056\uffcd\057\uffcd" +
    "\060\uffcd\061\uffcd\063\uffcd\001\002\000\036\030\072\031" +
    "\066\032\076\033\074\034\067\043\071\044\070\045\077" +
    "\046\073\047\102\050\100\051\065\052\101\055\075\001" +
    "\002\000\036\015\046\025\053\026\047\027\054\031\045" +
    "\053\056\054\061\063\052\064\055\065\063\066\060\067" +
    "\050\070\051\071\062\001\002\000\036\015\046\025\053" +
    "\026\047\027\054\031\045\053\056\054\061\063\052\064" +
    "\055\065\063\066\060\067\050\070\051\071\062\001\002" +
    "\000\036\015\046\025\053\026\047\027\054\031\045\053" +
    "\056\054\061\063\052\064\055\065\063\066\060\067\050" +
    "\070\051\071\062\001\002\000\036\015\046\025\053\026" +
    "\047\027\054\031\045\053\056\054\061\063\052\064\055" +
    "\065\063\066\060\067\050\070\051\071\062\001\002\000" +
    "\036\015\046\025\053\026\047\027\054\031\045\053\056" +
    "\054\061\063\052\064\055\065\063\066\060\067\050\070" +
    "\051\071\062\001\002\000\036\015\046\025\053\026\047" +
    "\027\054\031\045\053\056\054\061\063\052\064\055\065" +
    "\063\066\060\067\050\070\051\071\062\001\002\000\036" +
    "\015\046\025\053\026\047\027\054\031\045\053\056\054" +
    "\061\063\052\064\055\065\063\066\060\067\050\070\051" +
    "\071\062\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\064\004" +
    "\uffce\007\uffce\011\uffce\012\uffce\013\uffce\024\uffce\030\uffce" +
    "\031\uffce\032\uffce\033\uffce\034\uffce\043\uffce\044\uffce\045" +
    "\uffce\046\uffce\047\uffce\050\uffce\051\uffce\052\uffce\055\uffce" +
    "\056\uffce\057\uffce\060\uffce\061\uffce\063\uffce\001\002\000" +
    "\036\015\046\025\053\026\047\027\054\031\045\053\056" +
    "\054\061\063\052\064\055\065\063\066\060\067\050\070" +
    "\051\071\062\001\002\000\036\015\046\025\053\026\047" +
    "\027\054\031\045\053\056\054\061\063\052\064\055\065" +
    "\063\066\060\067\050\070\051\071\062\001\002\000\036" +
    "\015\046\025\053\026\047\027\054\031\045\053\056\054" +
    "\061\063\052\064\055\065\063\066\060\067\050\070\051" +
    "\071\062\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\036\015" +
    "\046\025\053\026\047\027\054\031\045\053\056\054\061" +
    "\063\052\064\055\065\063\066\060\067\050\070\051\071" +
    "\062\001\002\000\064\004\uffd4\007\uffd4\011\uffd4\012\uffd4" +
    "\013\uffd4\024\uffd4\030\072\031\066\032\076\033\074\034" +
    "\067\043\uffd4\044\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4" +
    "\051\uffd4\052\uffd4\055\uffd4\056\uffd4\057\uffd4\060\uffd4\061" +
    "\uffd4\063\uffd4\001\002\000\064\004\uffd1\007\uffd1\011\uffd1" +
    "\012\uffd1\013\uffd1\024\uffd1\030\072\031\066\032\076\033" +
    "\074\034\067\043\071\044\070\045\077\046\073\047\102" +
    "\050\100\051\065\052\uffd1\055\uffd1\056\uffd1\057\uffd1\060" +
    "\uffd1\061\uffd1\063\uffd1\001\002\000\064\004\uffd3\007\uffd3" +
    "\011\uffd3\012\uffd3\013\uffd3\024\uffd3\030\072\031\066\032" +
    "\076\033\074\034\067\043\uffd3\044\uffd3\045\uffd3\046\uffd3" +
    "\047\uffd3\050\uffd3\051\uffd3\052\uffd3\055\uffd3\056\uffd3\057" +
    "\uffd3\060\uffd3\061\uffd3\063\uffd3\001\002\000\064\004\uffd6" +
    "\007\uffd6\011\uffd6\012\uffd6\013\uffd6\024\uffd6\030\072\031" +
    "\066\032\076\033\074\034\067\043\uffd6\044\uffd6\045\uffd6" +
    "\046\uffd6\047\uffd6\050\uffd6\051\uffd6\052\uffd6\055\uffd6\056" +
    "\uffd6\057\uffd6\060\uffd6\061\uffd6\063\uffd6\001\002\000\064" +
    "\004\uffdb\007\uffdb\011\uffdb\012\uffdb\013\uffdb\024\uffdb\030" +
    "\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\043\uffdb\044\uffdb" +
    "\045\uffdb\046\uffdb\047\uffdb\050\uffdb\051\uffdb\052\uffdb\055" +
    "\uffdb\056\uffdb\057\uffdb\060\uffdb\061\uffdb\063\uffdb\001\002" +
    "\000\064\004\uffda\007\uffda\011\uffda\012\uffda\013\uffda\024" +
    "\uffda\030\uffda\031\uffda\032\uffda\033\uffda\034\uffda\043\uffda" +
    "\044\uffda\045\uffda\046\uffda\047\uffda\050\uffda\051\uffda\052" +
    "\uffda\055\uffda\056\uffda\057\uffda\060\uffda\061\uffda\063\uffda" +
    "\001\002\000\064\004\uffd5\007\uffd5\011\uffd5\012\uffd5\013" +
    "\uffd5\024\uffd5\030\072\031\066\032\076\033\074\034\067" +
    "\043\uffd5\044\uffd5\045\uffd5\046\uffd5\047\uffd5\050\uffd5\051" +
    "\uffd5\052\uffd5\055\uffd5\056\uffd5\057\uffd5\060\uffd5\061\uffd5" +
    "\063\uffd5\001\002\000\064\004\uffdd\007\uffdd\011\uffdd\012" +
    "\uffdd\013\uffdd\024\uffdd\030\uffdd\031\uffdd\032\076\033\074" +
    "\034\067\043\uffdd\044\uffdd\045\uffdd\046\uffdd\047\uffdd\050" +
    "\uffdd\051\uffdd\052\uffdd\055\uffdd\056\uffdd\057\uffdd\060\uffdd" +
    "\061\uffdd\063\uffdd\001\002\000\064\004\uffd8\007\uffd8\011" +
    "\uffd8\012\uffd8\013\uffd8\024\uffd8\030\072\031\066\032\076" +
    "\033\074\034\067\043\uffd8\044\uffd8\045\077\046\073\047" +
    "\102\050\100\051\uffd8\052\uffd8\055\uffd8\056\uffd8\057\uffd8" +
    "\060\uffd8\061\uffd8\063\uffd8\001\002\000\064\004\uffd7\007" +
    "\uffd7\011\uffd7\012\uffd7\013\uffd7\024\uffd7\030\072\031\066" +
    "\032\076\033\074\034\067\043\uffd7\044\uffd7\045\077\046" +
    "\073\047\102\050\100\051\uffd7\052\uffd7\055\uffd7\056\uffd7" +
    "\057\uffd7\060\uffd7\061\uffd7\063\uffd7\001\002\000\064\004" +
    "\uffd9\007\uffd9\011\uffd9\012\uffd9\013\uffd9\024\uffd9\030\uffd9" +
    "\031\uffd9\032\uffd9\033\uffd9\034\uffd9\043\uffd9\044\uffd9\045" +
    "\uffd9\046\uffd9\047\uffd9\050\uffd9\051\uffd9\052\uffd9\055\uffd9" +
    "\056\uffd9\057\uffd9\060\uffd9\061\uffd9\063\uffd9\001\002\000" +
    "\064\004\uffdc\007\uffdc\011\uffdc\012\uffdc\013\uffdc\024\uffdc" +
    "\030\uffdc\031\uffdc\032\076\033\074\034\067\043\uffdc\044" +
    "\uffdc\045\uffdc\046\uffdc\047\uffdc\050\uffdc\051\uffdc\052\uffdc" +
    "\055\uffdc\056\uffdc\057\uffdc\060\uffdc\061\uffdc\063\uffdc\001" +
    "\002\000\064\004\uffd2\007\uffd2\011\uffd2\012\uffd2\013\uffd2" +
    "\024\uffd2\030\072\031\066\032\076\033\074\034\067\043" +
    "\071\044\070\045\077\046\073\047\102\050\100\051\uffd2" +
    "\052\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2\061\uffd2\063" +
    "\uffd2\001\002\000\064\004\uffd0\007\uffd0\011\uffd0\012\uffd0" +
    "\013\uffd0\024\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034" +
    "\uffd0\043\uffd0\044\uffd0\045\uffd0\046\uffd0\047\uffd0\050\uffd0" +
    "\051\uffd0\052\uffd0\055\uffd0\056\uffd0\057\uffd0\060\uffd0\061" +
    "\uffd0\063\uffd0\001\002\000\036\015\046\025\053\026\047" +
    "\027\054\031\045\053\056\054\061\063\052\064\055\065" +
    "\063\066\060\067\050\070\051\071\062\001\002\000\036" +
    "\030\072\031\066\032\076\033\074\034\067\043\071\044" +
    "\070\045\077\046\073\047\102\050\100\051\065\052\101" +
    "\055\123\001\002\000\004\062\124\001\002\000\004\063" +
    "\125\001\002\000\004\054\126\001\002\000\004\055\127" +
    "\001\002\000\064\004\uffc3\007\uffc3\011\uffc3\012\uffc3\013" +
    "\uffc3\024\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\034\uffc3" +
    "\043\uffc3\044\uffc3\045\uffc3\046\uffc3\047\uffc3\050\uffc3\051" +
    "\uffc3\052\uffc3\055\uffc3\056\uffc3\057\uffc3\060\uffc3\061\uffc3" +
    "\063\uffc3\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\036\030" +
    "\072\031\066\032\076\033\074\034\067\043\071\044\070" +
    "\045\077\046\073\047\102\050\100\051\065\052\101\055" +
    "\132\001\002\000\064\004\uffc5\007\uffc5\011\uffc5\012\uffc5" +
    "\013\uffc5\024\uffc5\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034" +
    "\uffc5\043\uffc5\044\uffc5\045\uffc5\046\uffc5\047\uffc5\050\uffc5" +
    "\051\uffc5\052\uffc5\055\uffc5\056\uffc5\057\uffc5\060\uffc5\061" +
    "\uffc5\063\uffc5\001\002\000\036\015\046\025\053\026\047" +
    "\027\054\031\045\053\056\054\061\063\052\064\055\065" +
    "\063\066\060\067\050\070\051\071\062\001\002\000\036" +
    "\030\072\031\066\032\076\033\074\034\067\043\071\044" +
    "\070\045\077\046\073\047\102\050\100\051\065\052\101" +
    "\055\135\001\002\000\064\004\uffc4\007\uffc4\011\uffc4\012" +
    "\uffc4\013\uffc4\024\uffc4\030\uffc4\031\uffc4\032\uffc4\033\uffc4" +
    "\034\uffc4\043\uffc4\044\uffc4\045\uffc4\046\uffc4\047\uffc4\050" +
    "\uffc4\051\uffc4\052\uffc4\055\uffc4\056\uffc4\057\uffc4\060\uffc4" +
    "\061\uffc4\063\uffc4\001\002\000\064\004\uffcf\007\uffcf\011" +
    "\uffcf\012\uffcf\013\uffcf\024\uffcf\030\uffcf\031\uffcf\032\uffcf" +
    "\033\uffcf\034\uffcf\043\uffcf\044\uffcf\045\uffcf\046\uffcf\047" +
    "\uffcf\050\uffcf\051\uffcf\052\uffcf\055\uffcf\056\uffcf\057\uffcf" +
    "\060\uffcf\061\uffcf\063\uffcf\001\002\000\060\004\ufff1\007" +
    "\ufff1\011\ufff1\012\ufff1\013\ufff1\024\ufff1\030\072\031\066" +
    "\032\076\033\074\034\067\043\071\044\070\045\077\046" +
    "\073\047\102\050\100\051\065\052\101\056\ufff1\057\ufff1" +
    "\061\ufff1\063\ufff1\001\002\000\060\004\uffea\007\uffea\011" +
    "\uffea\012\uffea\013\uffea\024\uffea\030\072\031\066\032\076" +
    "\033\074\034\067\043\071\044\070\045\077\046\073\047" +
    "\102\050\100\051\065\052\101\056\uffea\057\uffea\061\uffea" +
    "\063\uffea\001\002\000\060\004\uffe9\007\uffe9\011\uffe9\012" +
    "\uffe9\013\uffe9\024\uffe9\030\072\031\066\032\076\033\074" +
    "\034\067\043\071\044\070\045\077\046\073\047\102\050" +
    "\100\051\065\052\101\056\uffe9\057\uffe9\061\uffe9\063\uffe9" +
    "\001\002\000\036\030\072\031\066\032\076\033\074\034" +
    "\067\043\071\044\070\045\077\046\073\047\102\050\100" +
    "\051\065\052\101\056\143\001\002\000\024\004\ufffe\007" +
    "\ufffe\011\ufffe\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe" +
    "\063\ufffe\001\002\000\024\004\023\007\024\011\016\012" +
    "\032\013\026\024\022\056\015\057\145\063\025\001\002" +
    "\000\026\004\uffe6\007\uffe6\010\146\011\uffe6\012\uffe6\013" +
    "\uffe6\024\uffe6\056\uffe6\057\uffe6\063\uffe6\001\002\000\006" +
    "\007\024\056\147\001\002\000\024\004\ufffe\007\ufffe\011" +
    "\ufffe\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe\063\ufffe" +
    "\001\002\000\024\004\uffe4\007\uffe4\011\uffe4\012\uffe4\013" +
    "\uffe4\024\uffe4\056\uffe4\057\uffe4\063\uffe4\001\002\000\024" +
    "\004\023\007\024\011\016\012\032\013\026\024\022\056" +
    "\015\057\152\063\025\001\002\000\024\004\uffe5\007\uffe5" +
    "\011\uffe5\012\uffe5\013\uffe5\024\uffe5\056\uffe5\057\uffe5\063" +
    "\uffe5\001\002\000\014\017\154\020\155\021\161\022\160" +
    "\023\157\001\002\000\030\004\ufff0\007\ufff0\011\ufff0\012" +
    "\ufff0\013\ufff0\024\ufff0\037\ufff0\056\ufff0\057\ufff0\061\ufff0" +
    "\063\ufff0\001\002\000\030\004\uffef\007\uffef\011\uffef\012" +
    "\uffef\013\uffef\024\uffef\037\uffef\056\uffef\057\uffef\061\uffef" +
    "\063\uffef\001\002\000\030\004\ufff2\007\ufff2\011\ufff2\012" +
    "\ufff2\013\ufff2\024\ufff2\037\162\056\ufff2\057\ufff2\061\ufff2" +
    "\063\ufff2\001\002\000\030\004\uffec\007\uffec\011\uffec\012" +
    "\uffec\013\uffec\024\uffec\037\uffec\056\uffec\057\uffec\061\uffec" +
    "\063\uffec\001\002\000\030\004\uffed\007\uffed\011\uffed\012" +
    "\uffed\013\uffed\024\uffed\037\uffed\056\uffed\057\uffed\061\uffed" +
    "\063\uffed\001\002\000\030\004\uffee\007\uffee\011\uffee\012" +
    "\uffee\013\uffee\024\uffee\037\uffee\056\uffee\057\uffee\061\uffee" +
    "\063\uffee\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\060\004" +
    "\ufff3\007\ufff3\011\ufff3\012\ufff3\013\ufff3\024\ufff3\030\072" +
    "\031\066\032\076\033\074\034\067\043\071\044\070\045" +
    "\077\046\073\047\102\050\100\051\065\052\101\056\ufff3" +
    "\057\ufff3\061\ufff3\063\ufff3\001\002\000\040\015\046\025" +
    "\053\026\047\027\054\031\045\053\056\054\061\055\166" +
    "\063\052\064\055\065\063\066\060\067\050\070\051\071" +
    "\062\001\002\000\006\055\171\060\170\001\002\000\026" +
    "\004\uffe0\007\uffe0\011\uffe0\012\uffe0\013\uffe0\024\uffe0\056" +
    "\uffe0\057\uffe0\061\uffe0\063\uffe0\001\002\000\040\030\072" +
    "\031\066\032\076\033\074\034\067\043\071\044\070\045" +
    "\077\046\073\047\102\050\100\051\065\052\101\055\uffde" +
    "\060\uffde\001\002\000\036\015\046\025\053\026\047\027" +
    "\054\031\045\053\056\054\061\063\052\064\055\065\063" +
    "\066\060\067\050\070\051\071\062\001\002\000\026\004" +
    "\uffe1\007\uffe1\011\uffe1\012\uffe1\013\uffe1\024\uffe1\056\uffe1" +
    "\057\uffe1\061\uffe1\063\uffe1\001\002\000\040\030\072\031" +
    "\066\032\076\033\074\034\067\043\071\044\070\045\077" +
    "\046\073\047\102\050\100\051\065\052\101\055\uffdf\060" +
    "\uffdf\001\002\000\024\004\ufffa\007\ufffa\011\ufffa\012\ufffa" +
    "\013\ufffa\024\ufffa\056\ufffa\057\ufffa\063\ufffa\001\002\000" +
    "\004\061\202\001\002\000\040\030\uffc6\031\uffc6\032\uffc6" +
    "\033\uffc6\034\uffc6\040\041\043\uffc6\044\uffc6\045\uffc6\046" +
    "\uffc6\047\uffc6\050\uffc6\051\uffc6\052\uffc6\056\uffc6\001\002" +
    "\000\036\030\072\031\066\032\076\033\074\034\067\043" +
    "\071\044\070\045\077\046\073\047\102\050\100\051\065" +
    "\052\101\056\177\001\002\000\024\004\ufffe\007\ufffe\011" +
    "\ufffe\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe\063\ufffe" +
    "\001\002\000\024\004\023\007\024\011\016\012\032\013" +
    "\026\024\022\056\015\057\201\063\025\001\002\000\024" +
    "\004\uffe3\007\uffe3\011\uffe3\012\uffe3\013\uffe3\024\uffe3\056" +
    "\uffe3\057\uffe3\063\uffe3\001\002\000\036\015\046\025\053" +
    "\026\047\027\054\031\045\053\056\054\061\063\052\064" +
    "\055\065\063\066\060\067\050\070\051\071\062\001\002" +
    "\000\036\030\072\031\066\032\076\033\074\034\067\043" +
    "\071\044\070\045\077\046\073\047\102\050\100\051\065" +
    "\052\101\061\204\001\002\000\004\063\205\001\002\000" +
    "\014\035\042\036\043\037\044\041\040\042\037\001\002" +
    "\000\004\056\207\001\002\000\024\004\ufffe\007\ufffe\011" +
    "\ufffe\012\ufffe\013\ufffe\024\ufffe\056\ufffe\057\ufffe\063\ufffe" +
    "\001\002\000\024\004\023\007\024\011\016\012\032\013" +
    "\026\024\022\056\015\057\211\063\025\001\002\000\024" +
    "\004\uffe2\007\uffe2\011\uffe2\012\uffe2\013\uffe2\024\uffe2\056" +
    "\uffe2\057\uffe2\063\uffe2\001\002\000\024\004\023\007\024" +
    "\011\016\012\032\013\026\024\022\056\015\057\213\063" +
    "\025\001\002\000\024\004\ufff4\007\ufff4\011\ufff4\012\ufff4" +
    "\013\ufff4\024\ufff4\056\ufff4\057\ufff4\063\ufff4\001\002\000" +
    "\024\004\ufffb\007\ufffb\011\ufffb\012\ufffb\013\ufffb\024\ufffb" +
    "\056\ufffb\057\ufffb\063\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\212\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\012\001\001\000" +
    "\016\004\017\010\013\011\020\012\016\013\030\014\026" +
    "\001\001\000\004\015\213\001\001\000\004\003\211\001" +
    "\001\000\006\005\175\010\173\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\172\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\141\001\001\000\002" +
    "\001\001\000\004\015\035\001\001\000\004\015\034\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\015\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\140\001\001\000\004" +
    "\005\137\001\001\000\004\005\136\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\056\001\001\000\004" +
    "\005\135\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\117\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\116\001\001\000\004\005\115" +
    "\001\001\000\004\005\114\001\001\000\004\005\113\001" +
    "\001\000\004\005\112\001\001\000\004\005\111\001\001" +
    "\000\004\005\110\001\001\000\004\005\107\001\001\000" +
    "\002\001\001\000\004\005\106\001\001\000\004\005\105" +
    "\001\001\000\004\005\104\001\001\000\004\005\103\001" +
    "\001\000\004\005\102\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\121\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\133\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\143\001\001\000\016\004\017\010\013\011\020\012" +
    "\016\013\030\014\026\001\001\000\002\001\001\000\004" +
    "\012\147\001\001\000\004\003\150\001\001\000\002\001" +
    "\001\000\016\004\017\010\013\011\020\012\016\013\030" +
    "\014\026\001\001\000\002\001\001\000\004\007\155\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\162\001\001\000\002\001\001\000\006\005\166" +
    "\006\164\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\171\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\177\001\001" +
    "\000\016\004\017\010\013\011\020\012\016\013\030\014" +
    "\026\001\001\000\002\001\001\000\004\005\202\001\001" +
    "\000\002\001\001\000\004\011\205\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\207\001\001\000\016" +
    "\004\017\010\013\011\020\012\016\013\030\014\026\001" +
    "\001\000\002\001\001\000\016\004\017\010\013\011\020" +
    "\012\016\013\030\014\026\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            String msg = "Error sintáctico cerca de '" + s.value + "'";
            com.golite.interpreter.Interprete.getInstancia()
                .agregarError(msg, s.left, s.right, "sintáctico");
            System.err.println(msg + " línea " + s.left);
        } else {
            com.golite.interpreter.Interprete.getInstancia()
                .agregarError(message, 0, 0, "sintáctico");
        }
    }
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoPrograma start_val = (NodoPrograma)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= FUNC MAIN LPAREN RPAREN LBRACE stmt_list RBRACE 
            {
              NodoPrograma RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> s = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoPrograma(s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // stmt_list ::= stmt_list stmt 
            {
              List<NodoAST> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST s = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 sl.add(s); RESULT = sl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt_list ::= 
            {
              List<NodoAST> RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // opt_semi ::= SEMICOLON 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // opt_semi ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= decl_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST d = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= assign_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAsignacion a = (NodoAsignacion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= if_stmt 
            {
              NodoAST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoIf i = (NodoIf)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= for_stmt 
            {
              NodoAST RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST f = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= print_stmt opt_semi 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST p = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= BREAK opt_semi 
            {
              NodoAST RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoBreak(bleft, bright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= CONTINUE opt_semi 
            {
              NodoAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoContinue(cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> sl = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoBloque(sl, 0, 0); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decl_stmt ::= VAR ID tipo ASSIGN expr 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, t, e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // decl_stmt ::= VAR ID tipo 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, t, null, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // decl_stmt ::= ID DECL_ASSIGN expr 
            {
              NodoAST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDeclaracion(n, null, e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= TINT 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= TFLOAT64 
            {
              String RESULT =null;
		 RESULT = "float64"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= TSTRING 
            {
              String RESULT =null;
		 RESULT = "string"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= TBOOL 
            {
              String RESULT =null;
		 RESULT = "bool"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo ::= TRUNE 
            {
              String RESULT =null;
		 RESULT = "rune"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // assign_stmt ::= ID ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // assign_stmt ::= ID PLUS_ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "+=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // assign_stmt ::= ID MINUS_ASSIGN expr 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoAsignacion(n, "-=", e, nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // assign_stmt ::= ID INC 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAsignacion(n, "+=", new NodoEntero(1, nleft, nright), nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // assign_stmt ::= ID DEC 
            {
              NodoAsignacion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAsignacion(n, "-=", new NodoEntero(1, nleft, nright), nleft, nright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // if_stmt ::= IF expr LBRACE stmt_list RBRACE 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoIf(c, t, null, null, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // if_stmt ::= IF expr LBRACE stmt_list RBRACE ELSE LBRACE stmt_list RBRACE 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> e = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoIf(c, t, e, null, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // if_stmt ::= IF expr LBRACE stmt_list RBRACE ELSE if_stmt 
            {
              NodoIf RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List<NodoAST> t = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eiright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoIf ei = (NodoIf)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoIf(c, t, null, ei, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // for_stmt ::= FOR expr LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> b = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoFor(c, null, null, b, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // for_stmt ::= FOR decl_stmt SEMICOLON expr SEMICOLON assign_stmt LBRACE stmt_list RBRACE 
            {
              NodoAST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		NodoAST i = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST c = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		NodoAsignacion u = (NodoAsignacion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> b = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoFor(c, i, u, b, cleft, cright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // print_stmt ::= PRINTLN LPAREN expr_list RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoAST> args = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoPrintln(args, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("print_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // print_stmt ::= PRINTLN LPAREN RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new NodoPrintln(new ArrayList<>(), pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("print_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr_list ::= expr_list COMMA expr 
            {
              List<NodoAST> RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoAST> el = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 el.add(e); RESULT = el; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr_list ::= expr 
            {
              List<NodoAST> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<NodoAST> l = new ArrayList<>(); l.add(e); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr PLUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoSuma(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr MINUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoResta(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr TIMES expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoMultiplicacion(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr DIV expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDivision(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr MOD expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoModulo(a, b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr EQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "==", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr NEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "!=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr LT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "<",  b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr GT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, ">",  b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr LEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, "<=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr GEQ expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoComparacion(a, ">=", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr AND expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "&&", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr OR expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST b = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "||", b, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= NOT expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLogico(a, "!", null, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= MINUS expr 
            {
              NodoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoAST a = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoNegacion(a, aleft, aright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= INT_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoEntero(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= FLOAT_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double v = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoDecimal(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= STRING_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoString(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= TRUE 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Boolean v = (Boolean)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoBooleano(true,  vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= FALSE 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Boolean v = (Boolean)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoBooleano(false, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= NIL 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoEntero(0, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= RUNE_LIT 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Character v = (Character)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoRune(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= ID 
            {
              NodoAST RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoIdentificador(v, vleft, vright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= ATOI LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoAtoi(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= PARSEFLOAT LPAREN expr RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new NodoParseFloat(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= TYPEOF LPAREN expr RPAREN DOT ID LPAREN RPAREN 
            {
              NodoAST RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		 RESULT = new NodoTypeOf(e, pleft, pright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
